//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPA.Core.Data.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public class DeviceInfo
    {
        [Required(ErrorMessage="DeviceInfoID is Required.")]
    	public int DeviceInfoID { get; set; }
        [Required(ErrorMessage="DeviceID is Required.")]
    	public long DeviceID { get; set; }
        [Required(ErrorMessage="GroupKey is Required.")]
    	[MaxLength(150)]
    	public string GroupKey { get; set; }
        [Required(ErrorMessage="KeyName is Required.")]
    	[MaxLength(150)]
    	public string KeyName { get; set; }
        [Required(ErrorMessage="KeyValue is Required.")]
    	[MaxLength(150)]
    	public string KeyValue { get; set; }
    
        public virtual Device Device { get; set; }
    
    }
}
