//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPA.Core.Data.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public class Manufacturer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manufacturer()
        {
            this.Devices = new HashSet<Device>();
            this.Models = new HashSet<Model>();
///            this.PackageDeploys = new HashSet<PackageDeploy>();
        }
        [Required(ErrorMessage="ManufacturerID is Required.")]
    	public int ManufacturerID { get; set; }
        [Required(ErrorMessage="MfgCode is Required.")]
    	[MaxLength(16)]
    	public string MfgCode { get; set; }
        [Required(ErrorMessage="MfgName is Required.")]
    	[MaxLength(50)]
    	public string MfgName { get; set; }
        [Required(ErrorMessage="StandardWarrantyID is Required.")]
    	public int StandardWarrantyID { get; set; }
        [Required(ErrorMessage="LastReplication is Required.")]
    	public System.DateTimeOffset LastReplication { get; set; }
        [Required(ErrorMessage="Active is Required.")]
    	public bool Active { get; set; }
        [Required(ErrorMessage="CreatedDate is Required.")]
    	public System.DateTimeOffset CreatedDate { get; set; }
        [Required(ErrorMessage="CreatedBy is Required.")]
    	[MaxLength(100)]
    	public string CreatedBy { get; set; }
        [Required(ErrorMessage="UpdatedDate is Required.")]
    	public System.DateTimeOffset UpdatedDate { get; set; }
        [Required(ErrorMessage="UpdatedBy is Required.")]
    	[MaxLength(100)]
    	public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Model> Models { get; set; }
///        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
///        public virtual ICollection<PackageDeploy> PackageDeploys { get; set; }
    
    }
}
